"use client";

import React from 'react';
import { ShieldAlert, Percent, Gavel } from 'lucide-react';

const TransparencyCard = ({ title, body, icon: Icon, colorClass }: { title: string, body: string, icon: any, colorClass: string }) => {
  return (
    <div className={`relative group overflow-hidden rounded-3xl border border-white/5 bg-slate-900/40 p-8 transition-all duration-500 hover:translate-y-[-4px] hover:border-${colorClass}/40`}>
      {/* Scanline Overlay */}
      <div className="absolute inset-0 pointer-events-none bg-[linear-gradient(rgba(18,16,16,0)_50%,rgba(0,0,0,0.05)_50%)] bg-[length:100%_4px] opacity-20" />
      
      {/* Glow Effect */}
      <div className={`absolute -top-24 -right-24 h-48 w-48 rounded-full bg-${colorClass}/10 blur-[60px] group-hover:bg-${colorClass}/20 transition-colors`} />

      <div className="relative z-10 space-y-4">
        <div className={`h-12 w-12 rounded-xl bg-slate-950 border border-${colorClass}/30 flex items-center justify-center mb-6`}>
          <Icon className={`text-${colorClass === 'pink-500' ? 'pink-400' : colorClass === 'cyan-500' ? 'cyan-400' : 'indigo-400'}`} size={24} />
        </div>
        
        <h4 className="text-xl font-black italic text-white uppercase tracking-tight leading-none">
          {title}
        </h4>
        
        <p className="text-sm font-medium text-slate-400 leading-relaxed">
          {body}
        </p>
      </div>
      
      {/* Bottom Accent Line */}
      <div className={`absolute bottom-0 left-0 h-[2px] w-0 bg-gradient-to-r from-${colorClass} to-transparent group-hover:w-full transition-all duration-700`} />
    </div>
  );
};

const TransparencySection = () => {
  return (
    <section className="space-y-12">
      <div className="flex items-center gap-4">
        <div className="h-[1px] w-12 bg-pink-500/50" />
        <h3 className="text-2xl font-black italic text-white uppercase tracking-[0.2em] text-glow">
          System Transparency
        </h3>
        <div className="h-[1px] flex-1 bg-gradient-to-r from-pink-500/50 to-transparent" />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        <TransparencyCard 
          title="0% Deposit Fees. 10% Performance."
          body="Vyrr only wins when you do. We charge zero management or deposit fees. We take a flat 10% cut of the yield generated by our routing engine. If you don't earn, we don't charge."
          icon={Percent}
          colorClass="pink-500"
        />
        
        <TransparencyCard 
          title="Non-Custodial Architecture."
          body="Your keys, your crypto. Vyrr never takes custody of your funds. Our router instantly deploys your capital to audited third-party vaults. You maintain 100% ownership and can withdraw at any time."
          icon={ShieldAlert}
          colorClass="cyan-500"
        />
        
        <TransparencyCard 
          title="Self-Sovereign Reporting."
          body="Vyrr is a decentralized interface. We do not collect personal data or tax information. Users are responsible for their own tax reporting via standard blockchain accounting tools."
          icon={Gavel}
          colorClass="indigo-500"
        />
      </div>
    </section>
  );
};

export default TransparencySection;